SELECT 
    COUNT(*) AS COUNT
FROM 
    (SELECT RIGHT(BIN(GENOTYPE), 4) AS GENOTYPE
     FROM ECOLI_DATA) AS TYPE
WHERE
    SUBSTRING(LPAD(TYPE.GENOTYPE, 4, '0'),-2, 1) = '0'
AND
    (SUBSTRING(LPAD(TYPE.GENOTYPE, 4, '0'),-3, 1) = '1'
     OR SUBSTRING(LPAD(TYPE.GENOTYPE, 4, '0'),-1, 1) = '1');